### ISSUE TITLE
ISO With single wim index

### ISSUE THREAD

**Issue by marrowgroup** [rbalsleyMSFT/FFU#10]
We are using a custom Windows 10 and 11 ISO with a single wim index. We can only run this with an ISO that has multiple wim index. Please provide a way for us to mounted ISO images where there is just a single wim index.

**Comment by rbalsleyMSFT** [comment]
Thanks. I'll look into it for the next release. I'm curious though, what's in the custom WIM?

**Comment by marrowgroup** [comment]
In the custom wim the following has been done

"RemoveAppxProvisionedPackage":  [

 "Microsoft.549981C3F5F10_1.1911.21713.0_neutral_~_8wekyb3d8bbwe",

 "Microsoft.BingWeather_4.25.20211.0_neutral_~_8wekyb3d8bbwe",

 "Microsoft.GetHelp_10.1706.13331.0_neutral_~_8wekyb3d8bbwe",

 "Microsoft.MicrosoftOfficeHub_18.1903.1152.0_neutral_~_8wekyb3d8bbwe",

 "Microsoft.MicrosoftSolitaireCollection_4.4.8204.0_neutral_~_8wekyb3d8bbwe",

 "Microsoft.MixedReality.Portal_2000.19081.1301.0_neutral_~_8wekyb3d8bbwe",

 "Microsoft.Office.OneNote_16001.12026.20112.0_neutral_~_8wekyb3d8bbwe",

 "Microsoft.People_2019.305.632.0_neutral_~_8wekyb3d8bbwe",

 "Microsoft.SkypeApp_14.53.77.0_neutral_~_kzf8qxf38zg5c",

 "Microsoft.Wallet_2.4.18324.0_neutral_~_8wekyb3d8bbwe",

 "Microsoft.WindowsFeedbackHub_2019.1111.2029.0_neutral_~_8wekyb3d8bbwe",

 "Microsoft.Xbox.TCUI_1.23.28002.0_neutral_~_8wekyb3d8bbwe",

 "Microsoft.XboxApp_48.49.31001.0_neutral_~_8wekyb3d8bbwe",

 "Microsoft.XboxGameOverlay_1.46.11001.0_neutral_~_8wekyb3d8bbwe",

 "Microsoft.XboxGamingOverlay_2.34.28001.0_neutral_~_8wekyb3d8bbwe",

 "Microsoft.XboxIdentityProvider_12.50.6001.0_neutral_~_8wekyb3d8bbwe",

 "Microsoft.XboxSpeechToTextOverlay_1.17.29001.0_neutral_~_8wekyb3d8bbwe",

 "Microsoft.YourPhone_2019.430.2026.0_neutral_~_8wekyb3d8bbwe",

 "Microsoft.ZuneMusic_2019.19071.19011.0_neutral_~_8wekyb3d8bbwe",

 "Microsoft.ZuneVideo_2019.19071.19011.0_neutral_~_8wekyb3d8bbwe"
                                     ],
    "RemoveWindowsCapability":  [
                                    "App.Support.QuickAssist~~~~0.0.1.0",
                                    "Browser.InternetExplorer~~~~0.0.11.0",
                                    "Microsoft.Windows.WordPad~~~~0.0.1.0"
                                ],
    "RemoveWindowsPackage":  [

 "Microsoft-OneCore-ApplicationModel-Sync-Desktop-FOD-Package~31bf3856ad364e35~amd64~~10.0.19041.1503",

 "Microsoft-OneCore-ApplicationModel-Sync-Desktop-FOD-Package~31bf3856ad364e35~amd64~~10.0.19041.1949",

 "Microsoft-Windows-InternetExplorer-Optional-Package~31bf3856ad364e35~amd64~~11.0.19041.1566",

 "Microsoft-Windows-QuickAssist-Package~31bf3856ad364e35~amd64~~10.0.19041.2364",

 "Microsoft-Windows-WordPad-FoD-Package~31bf3856ad364e35~amd64~~10.0.19041.1682",

 "Microsoft-Windows-WordPad-FoD-Package~31bf3856ad364e35~amd64~en-US~10.0.19041.1",

 "Microsoft-Windows-WordPad-FoD-Package~31bf3856ad364e35~wow64~~10.0.19041.1",

 "Microsoft-Windows-WordPad-FoD-Package~31bf3856ad364e35~wow64~en-US~10.0.19041.1"
                             ],
    "DisableWindowsOptionalFeature":  [

"Internet-Explorer-Optional-amd64",
                                          "MicrosoftWindowsPowerShellV2",
                                          "MicrosoftWindowsPowerShellV2Root"
                                      ],
    "EnableWindowsOptionalFeature":  [
                                         "Client-DeviceLockdown",
                                         "Client-EmbeddedBootExp",
                                         "Client-EmbeddedLogon"

**Comment by rbalsleyMSFT** [comment]
Fixed - [Commit](https://github.com/rbalsleyMSFT/FFU/commit/9e2da741d53652e6e600ca19cfd38f507bd01fde)
