### ISSUE TITLE
Just only Create a USB Stick

### ISSUE THREAD

**Issue by RonarPS** [rbalsleyMSFT/FFU#100]
Hi,

This is a greate Project, and i'dlike to use it for our Windows client deployment.

i do have one question, if it's possible to just only recreate the USB Stick, if no cleanup was done in a previous run. i've seen the USBImagingToolCreator.ps1 - but after execution only an empty stick was created.

do you have a hint for me?
thanks

**Comment by rbalsleyMSFT** [comment]
@MKellyCBSD might be able to help with the USBImagingToolCreator.ps1 file

**Comment by MKellyCBSD** [comment]
I have an updated version. I created a pull request #101 . 

1. Resolved an issue with the Images folder not being copied over
2. A progress bar has been added. It advances in segments, so it may appear to be frozen at times, but it is functioning correctly
3. Added an option to disable Autoplay to prevent empty volume errors during script execution

This script has to be run from within the root folder containing the **Drivers** and **Images** folders.
This script also must be run from an Admin PowerShell console

![image](https://github.com/user-attachments/assets/915bacfc-310e-4927-ab63-f492277bba89)

![image](https://github.com/user-attachments/assets/3e4cb021-334c-4e7a-8ef9-6cee82f636b3)


![image](https://github.com/user-attachments/assets/2f1fe5f3-59df-45d4-8258-722e4bea5a50)

**Comment by MKellyCBSD** [comment]
I'll have to check this later. I initially uploaded a pull request. but then realized that that script is different than the script on the main branch. sorry for the confusion.

**Comment by MKellyCBSD** [comment]
try the pull request I just submitted #102. Hope This helps. I tested this and it worked for me.

**Comment by MKellyCBSD** [comment]
try the pull request I just submitted #103 to 2410.1. Hope This helps. I tested this and it worked for me.

**Comment by RonarPS** [comment]
Thanks a lot for the fast response!
yes, now it's working :)

Gerat job! Keep on developing the solution! :)
