### ISSUE TITLE
ODT not downloadable

### ISSUE THREAD

**Issue by RonarPS** [rbalsleyMSFT/FFU#104]
Hi

Just recognized, that the ODT Download link is not able to be generated.

the function Get-ODTURL returns an empty value. Digged a little into it, and the requested URL 'https://www.microsoft.com/en-us/download/confirmation.aspx?id=49117' actually returns "Our services aren't available right now
We're working to restore all services as soon as possible. Please check back soon."

To get the framework running atm, i replaced the in the function "get-office" the "$ODTUrl = Get-ODTURL" with "ODTUrl = "https://download.microsoft.com/download/2/7/A/27AF1BE6-DD20-4CB4-B154-EBAB8A7D4A7E/officedeploymenttool_18129-20030.exe"  - the actual ODT Installation source.

Does anybody expirience the same issue?

Br

**Comment by eriksjogren** [comment]
@RonarPS, yes I have been since last Thursday.  Thought it was me to begin with.

**Comment by rbalsleyMSFT** [comment]
I see the same. I'll take a look.

**Comment by rbalsleyMSFT** [comment]
This should be fixed in 2410.1 now. Looks like the confirmation.aspx page is gone now and the details.aspx page has the URL to use. 

https://github.com/rbalsleyMSFT/FFU/tree/2410.1
