### ISSUE TITLE
CaptureFFU fails - network path not found

### ISSUE THREAD

**Issue by WIN-USER-BiT** [rbalsleyMSFT/FFU#105]
Windows 11 24H2 26100.2605 on my computer & an image I want to prepare

Network type "Private"

Once I click properties on "C:\FFUDevelopment\FFU" folder and select Share my computer hangs "explorer.exe" process

Control Panel - Computer Managment - Users - ffu_user - doesn't belong to any group, is it normal? (My OS is non-english)

Hyper V PC settings - Network Connections - sets to "No Connection" by default ...
Is there any way to assign external switch automatically?

![FFU](https://github.com/user-attachments/assets/8c9b5f5a-0c96-4f0f-a870-639aae39062c)
![FFU2](https://github.com/user-attachments/assets/6589595b-c484-4f49-be01-8192c4df61f8)

**Comment by rbalsleyMSFT** [comment]
Can you attach the C:\FFUDevelopment\FFUDevelopment.log file?

**Comment by rbalsleyMSFT** [comment]
I don't see anything here that looks wrong. Usually when the FFU doesn't get captured, it's related to the network switch configuration and not having the correct IP address. I recently added some code to validate that both the switch and IP match. If those are correct, then the next thing to look at is the ffu_user account and whether that's being created. The log says it is, but it's possible it's not and we're not handling the error like we should be.

Can you confirm if the ffu_user account is being created?

Can you also send over the C:\FFUDevelopment\WinPECaptureFFUFiles\CaptureFFU.ps1 file? The top of that file will have the ffu_user username and password that we use for the net use connection to map back to your host machine. I want to see if that's being written correctly too.

**Comment by rbalsleyMSFT** [comment]
> Windows 11 24H2 26100.2605 on my computer & an image I want to prepare
> 
> Network type "Private"
> 
> Once I click properties on "C:\FFUDevelopment\FFU" folder and select Share my computer hangs "explorer.exe" process
> 
> Control Panel - Computer Managment - Users - ffu_user - doesn't belong to any group, is it normal? (My OS is non-english)
> 
> Hyper V PC settings - Network Connections - sets to "No Connection" by default ... Is there any way to assign external switch automatically?
> 

Not sure why explorer would hang when selecting share on that folder. 

ffu_user doesn't belong to a group. It's just a standard user that has access to the FFUCaptureShare which maps to the FFUDevelopment\FFU folder to copy the FFU from the VM to the host machine. 

The VM originally has no network connection by default when the FFU is being built in Audit Mode. Once sysprep runs and the VM shuts down, the script attaches your VM switch that you specified and boots to PE. While in PE, it'll copy the FFU from the VM to your host via that switch.

**Comment by rbalsleyMSFT** [comment]
Closing since I haven't heard back in a week. Please reopen if you're still running into an issue.
