### ISSUE TITLE
Error when running script

### ISSUE THREAD

**Issue by samzin74** [rbalsleyMSFT/FFU#109]
I receive the following error when trying to run the install script: 

At C:\FFUDevelopment\BuildFFUVM.ps1:1801 char:26
+ ... MSWebPage = Invoke-RestMethod 'https://www.microsoft.com/en-us/downlo ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

- I worked around it by setting install office to false which is unfortunately not ideal. any assistance is appreciated!

**Comment by samzin74** [comment]
was able to get it to work on non work device.

**Comment by rbalsleyMSFT** [comment]
This is fixed in 2410.1 (which will be pushed to main later this week).

For now, you can download the 2410.1 from its branch here - https://github.com/rbalsleyMSFT/FFU/tree/2410.1

**Comment by samzin74** [comment]
Awesome, thank you!
