### ISSUE TITLE
Build process fails at M365 Apps/Office download step - Error 404

### ISSUE THREAD

**Issue by Em3xus-MW** [rbalsleyMSFT/FFU#110]
No changes from 1-2 weeks ago when the script worked. Now erroring out at M365 Apps/Office download step complaining that it cannot find the web resources.

This is my build command

.\BuildFFUVM.ps1 -ISOPath "C:\FFUDevelopment\ISO\SW_DVD9_Win_Pro_11_23H2.11_64BIT_English_Pro_Ent_EDU_N_MLF_X23-86376.ISO" -ProductKey "REDACTED" -Installapps $true -InstallOffice $true -CopyDrivers $false -VMSwitchName 'External' -VMHostIPAddress 'REDACTED' -CreateDeploymentMedia $true -BuildUSBDrive $false -UpdateLatestCU $true -UpdateLatestNet $true -UpdateLatestDefender $true -UpdateEdge $true -UpdateOneDrive $true -CopyPPKG $true -CopyUnattend $true -verbose

[FFUDevelopment.zip](https://github.com/user-attachments/files/18157777/FFUDevelopment.zip)

![Screenshot 2024-12-17 092137](https://github.com/user-attachments/assets/6b090538-22f4-43d9-b94e-f1408b63d606)

![Screenshot 2024-12-17 092149](https://github.com/user-attachments/assets/396aab85-9da5-4833-b054-10981a3b03be)

Thanks.

**Comment by rbalsleyMSFT** [comment]
Hi, see this.

https://github.com/rbalsleyMSFT/FFU/issues/109#issuecomment-2546401092

**Comment by Em3xus-MW** [comment]
> Hi, see this.
> 
> [#109 (comment)](https://github.com/rbalsleyMSFT/FFU/issues/109#issuecomment-2546401092)

Amazing thank you :) love your work.
