### ISSUE TITLE
Maybe not an issue? 

### ISSUE THREAD

**Issue by samzin74** [rbalsleyMSFT/FFU#112]
Apologies if this is not the place to put this. 

Where is there if any place to have unwanted programs to be removed from the image. ie outlook(new), teams (new), xbox etc. I have a script that I use to remove them however, not quite sure where/if able to add this to the FFU.

Thanks in advance!

**Comment by rbalsleyMSFT** [comment]
In the FFU Deep Dive video I explain how to add custom apps and commands here - https://www.youtube.com/watch?v=rqXRbgeeKSQ&t=2099s

**Comment by samzin74** [comment]
So add the remove commands below the REM line on the InstallAppsandSysprep batch file?

Thank you again

**Comment by rbalsleyMSFT** [comment]
You got it.
