### ISSUE TITLE
Feature Proposal - Automated App Downloads and Installs

### ISSUE THREAD

**Issue by zehadialam** [rbalsleyMSFT/FFU#30]
Richard,

I wanted to discuss a feature proposal with you before submitting a PR. I have been developing a function that leverages winget to automatically download a list of user-specified apps from a text file for inclusion in the FFU.

Example
![applist](https://github.com/rbalsleyMSFT/FFU/assets/63765084/b88c8002-8912-444a-ab73-893da78a9f7b)

The silent install switches from the yaml file downloaded by winget are extracted to construct a silent install command for each app. This is then appended to the InstallAppsandSysprep.cmd file.

![appsinstallcommands](https://github.com/rbalsleyMSFT/FFU/assets/63765084/176ea6e4-19b7-4418-a701-7e5c90d508c6)

Let me know your thoughts.

Thank you,
Zehadi

**Comment by rbalsleyMSFT** [comment]
Hi Zehadi, 

That's great!

I was looking at this the other day for the Company Portal. There's an experimental feature storeDownload, which is moving from preview to 1.8 in the near future. You can see the syntax on how to enable it from the releases page for the latest 1.9 preview release. https://github.com/microsoft/winget-cli/releases 

If you do download store apps too, you'll want to provision them, you'll have to make sure to handle the dependencies and also specify Regions All. I got bit by this last week when testing the viability of this and couldn't understand why Company Portal wasn't provisioning for all users.

This is what I was working with:

Dism /Online /Add-ProvisionedAppxPackage /PackagePath:C:\Test\Apps\MyPackedApp\MainPackage.appxbundle /DependencyPackagePath:C:\Test\Apps\MyPackedApp\Framework-x86.appx /DependencyPackagePath:C:\Test\Apps\MyPackedApp\Framework-x64.appx /LicensePath:C:\Test\Apps\MyLicense.xml (or /SkipLicense if no license downloads - CP doesn't seem to need a license) /Region:"all"

https://learn.microsoft.com/en-us/powershell/module/dism/add-appxprovisionedpackage?view=windowsserver2022-ps#-regions:~:text=When%20a%20list%20of%20regions%20is%20not%20specified%2C%20the%20package%20will%20be%20provisioned%20only%20if%20it%20is%20pinned%20to%20start%20layout.
 
I haven't written any code for this yet as I was testing manually. But I think if you can get the win32 and store apps in, that'd be awesome. I'll be out the next couple of weeks, but I'll be checking things on and off.

**Comment by zehadialam** [comment]
Sounds good, I'm happy to work on incorporating store apps. Thanks for the info and links!

--Zehadi

**Comment by zehadialam** [comment]
Hi Richard,

Let me know which branch I should submit the PR to.

--Zehadi

**Comment by rbalsleyMSFT** [comment]
Use 2407.1

**Comment by rbalsleyMSFT** [comment]
@zehadialam just wanted to give you a heads up that 2407 probably won't go out this week. Testing is going fine, but I'm running into some unexpected behavior updating the inbox store apps with the latest versions from winget. My idea was to update all of those old apps with the latest versions to keep things secure and reduce bandwidth. Currently I'm seeing about a 70% bandwidth savings using a fully updated FFU (latest CU, .NET, Defender, Edge, OneDrive, plus all of the inbox UWP apps). But I still see some apps update even though winget is providing the latest update. So I'm asking around if this is expected or if there's a better way to handle this.  

![image](https://github.com/user-attachments/assets/5bb624e3-72f7-454b-a566-30cb9a46f25b)

**Comment by zehadialam** [comment]
Interesting, thanks for the update. Which apps behave like this? I'd be interested in looking into this further.

**Comment by rbalsleyMSFT** [comment]
Too many to list. There are about 28 or so IIRC.
