### ISSUE TITLE
2401.1 Feature/Fix List

### ISSUE THREAD

**Issue by rbalsleyMSFT** [rbalsleyMSFT/FFU#4]
- If $buildUSBDrive -eq $true, check if USB drive is present
- When creating USB drive, give ability to copy drivers, PPKG, unattend, and autopilot json if present in the FFUDevelopment folder
- Create $RemoveFFU variable to control the removal of FFUs in the FFU folder so subsequent FFU creation doesn't prompt for FFU selection when building USB drive
- Create variables to control clean up of WinPE Capture/Deploy and Apps ISO files
- Revert code back to allow optimized FFUs to be applied via ApplyFFU.ps1 now that Sept 2023 ADK release has FFUProvider.dll fix
- Add option in Get-FFUEnvironment to clean out old VMs showing in Hyper-V if previous run failed. 
- Fixed an issue where Windows Updates wouldn't install for VHDX-only captures (e.g. when -installapps $false was set)
- Add the option for downloading the latest:
-- KB2267602 Defender definitions - https://go.microsoft.com/fwlink/?LinkID=121721&arch=x64
-- KB4052623 Defender Platform update - Update Catalog
-- KB5007651 Windows Security Platform Update - Update Catalog
-- Edge Stable
-- OneDrive per machine

Adding the above to the FFU will reduce the need for Windows to update all of these things at the same time after the OS is loaded.

- Add Compact switch to configure CompactOS. Currently all FFUs created for Windows client are compacted. 
- Add ability to copy PE Drivers to WinPE
- Change M365 Apps download to use Current Channel. It was using Monthly Enterprise before. Using ME will download a slightly older release, but it doesn't keep the machine on the ME channel once you update. So it makes sense to use Current channel instead, and the IT admin can adjust the channel via Intune.
- Added $optimize switch to control whether FFU is optimized. The FFU will be optimized by default, use -optimize $false if you want to disable the optimization of the FFU (setting -optimize $false shouldn't be necessary in most cases).
- Update docs to call out 4K Native drives need to use -LogicalSectorSizeBytes 4096. By default, FFUs use 512 for the LogicalSectorSizeBytes variable, and this works for most devices, but newer devices seem to be shipping with 4K Native or Advanced Format drives (UFS hard drives: Dell 3140, Lenovo 300W and 500W, etc. these aren't the only UFS models, these are the ones we've tested). If you see errors in the Scriptlog.txt such as "Failed to apply FFU - LastExitCode = 1393", this indicates that the LogicalSectorSizeBytes doesn't match what the disk supports. The reverse is true too. If you try and deploy a FFU that was captured with a LogicalSectorSizeBytes value of 4096 and the device only supports 512, you'll see the same "Failed to apply FFU - LastExitCode = 1393" error in Scriptlog.txt. 
- 4K FFU Servicing
-- Add check if $logicalSectorSizeBytes -eq 4096, prevent adding drivers as the mounting of the FFU causes it to become invalid.
-- Update docs to call out a current issue where a 4K FFUs have an issue being serviced.

**Comment by jaywatkins** [comment]
This is a great set of tools. Thank you!

Does the SSD of the target machine have to be in a certain condition prior to FFU application? ApplyFFU.ps1 throws an error indicating it "you cannot call a method on a null valued expression." Line 129, character 1 of the script. This happens if I wipe the SSD first with the BIOS utility or try to apply over an existing install.
