### ISSUE TITLE
Lenovo Driver Downloads Fail

### ISSUE THREAD

**Issue by rbalsleyMSFT** [rbalsleyMSFT/FFU#41]
Lenovo changed the PSREF page. Luckily it looks like they use an API now and it should be much easier to look up models. Will incorporate a fix soon and publish as 2407.2

**Comment by HedgeComp** [comment]
Just testing this now. You beat me to it. I am running a DriverGrabber from Lenovo. Do we need to extract the files and place them in the .\Drivers folder temporarily while you address this?

**Comment by rbalsleyMSFT** [comment]
It's fixed :)

https://github.com/rbalsleyMSFT/FFU/releases/tag/v2407.2
