### ISSUE TITLE
Using PPKG with USB 3.2 Gen2 drives

### ISSUE THREAD

**Issue by HedgeComp** [rbalsleyMSFT/FFU#46]
@rbalsleyMSFT , this has appeared to be more of a Microsoft OOBE limitation then a Bug in your code, but it should be noted in the documentation that when using larger drive capacity Flash Drives, 128GB and above, the Windows will not autoload the provisioning package. 

I've tested this with a few USB-C or A 3.2 Gen2 drives, which do not come in capacities lower than 128GB. I believe this has to do with the fact that they are now seen as external Hard Disks and not removable storage. Not sure if there is a directory you can place them in or a work around by copying into the FFU at the time of capture.

If I swap out the FFU drive and place a 64GB drive with the PPKG it will see it and load right away at the OOBE Language screen.

Perhaps this is something your contacts at Microsoft know about or a feature request can be made to fix, as more Gen2 drives are hitting the market, with PCs also using 10GBs ports now.

**Comment by rbalsleyMSFT** [comment]
Thanks, yeah, this is an issue with external hard disks vs removable media. Unfortunately, there's unlikely any appetite to fix this. Awhile back I did ask if there was a way to stage a PPKG from within PE, but our devs said there wasn't a way to handle that. My goal was to prevent the need to keep the USB drive in the machine any longer than necessary and let the PPKG get invoked as soon as OOBE began.
