### ISSUE TITLE
DISM version in Windows 11 23H2

### ISSUE THREAD

**Issue by mmanous01** [rbalsleyMSFT/FFU#5]
I updated a VM to Windows 11 23H2 via enablement package. The version of DISM did not change from 10.0.22621.1 to the 10.0.25XXX build where the Optimize-FFU switch is working. Did the fix not make it into the baked-in DISM? Will we have to use the Insider ADK's DISM for the foreseeable future (or at least until the 23H2 ADK is released)?

**Comment by rbalsleyMSFT** [comment]
The latest releases of the FFU repo don't require the Insider ADK any longer. I reverted the requirement for that. The FFUs are still optimized, but the script is still extending the windows partition and creating the recovery partition. If you haven't updated, I strongly recommend that you do.

The 22H2 September ADK does have the optimize-ffu fix in it. My plan is to work on a build this month to incorporate that so I can revert the manual partitioning I'm doing and clean up all the commented code that's in the script.

This is what I plan to work on this month (time permitting)

2311.1 Feature/Fix List * Issue #4 * rbalsleyMSFT/FFU (github.com)<https://github.com/rbalsleyMSFT/FFU/issues/4>

Thanks,
Richard

From: mmanous01 ***@***.***>
Sent: Thursday, November 2, 2023 6:44 AM
To: rbalsleyMSFT/FFU ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [rbalsleyMSFT/FFU] DISM version in Windows 11 23H2 (Issue #5)


I updated a VM to Windows 11 23H2 via enablement package. The version of DISM did not change from 10.0.22621.1 to the 10.0.25XXX build where the Optimize-FFU switch is working. Did the fix not make it into the baked-in DISM? Will we have to use the Insider ADK's DISM for the foreseeable future (or at least until the 23H2 ADK is released)?

-

**Comment by mmanous01** [comment]
I had been avoiding the September ADK since it lacked VBScript support out-of-the-box. Good to know that it has the Optimize-FFU fix in it though! That will simplify things for my purposes.

I didn't know about FFU imaging until I stumbled across your solution. I have to confess that I'm not using your FFU repo though you did give me a lot of good ideas to write my own version that is more MDT-ish. Thanks so much for putting it together.
