### ISSUE TITLE
Known Issue: Winget downloads fail on Non-English OS

### ISSUE THREAD

**Issue by rbalsleyMSFT** [rbalsleyMSFT/FFU#50]
The script will scrape the winget.exe text output to track search and download behavior. Since the script is matching against English language strings, other OS languages will fail to download apps. 

It appears that the Winget PowerShell module does include support for downloading both winget and msstore apps using the [Export-WingetPackage cmdlet](https://github.com/microsoft/winget-cli/blob/master/doc/specs/%23658%20-%20WinGet%20Download.md#winget-powershell-cmdlet). We'll get that converted for 2409.1.

**Comment by HedgeComp** [comment]
not sure if this helps in the planning but I noticed today after trouble shooting some failed Lenovo apps during the creating App ISO stage.,


![image](https://github.com/user-attachments/assets/54ba4b1c-ee72-48a1-a80a-360f9e641c1e)

 that if you remove the _--scope machine_  ,the app will then download. This was the issue with Lenovo Service bridge as an example.

![image](https://github.com/user-attachments/assets/8617e45e-8139-4ebc-aca5-aed4a7cedb16)
