### ISSUE TITLE
Deploy ISO not found after capture. Unable to build USB-drive

### ISSUE THREAD

**Issue by heremansgeert** [rbalsleyMSFT/FFU#55]
Hello,

After running the script the building of the USB-drive failes because the captured ISO cannot be found. 

The error is` 20-8-2024 11:34:50 True set to true, however unable to find C:\FFUDevelopment\WinPE_FFU_Deploy_x64.iso. USB drive not built.`. And indeed in this location no such file is present. I can however find it in `C:\FFUDevelopment\FFU`

My buildscript is:

```powershell
C:\FFUDevelopment\BuildFFUVM.ps1 -ISOPath 'C:\isos\SW_DVD9_Win_Pro_11_23H2.8_64BIT_Dutch_Pro_Ent_EDU_N_MLF_X23-78772.ISO' -WindowsRelease 11 -WindowsSKU 'Education' -UpdateLatestCU $true `
 -UpdateLatestNet $true -UpdateLatestDefender $true `
-InstallApps $true -InstallOffice $true  -ProductKey 'MYKEY-IS-CORRECT' -BuildUSBDrive $true `
-UpdateEdge $true -UpdateOneDrive $true -VMHostIPAddress '172.18.144.1' -VMSwitchName "Default Switch"  -verbose -WindowsLang 'nl-nl'
```

Anyone got an idea what might be wrong?

**Comment by HedgeComp** [comment]
@heremansgeert  try running the script again with the `-CreateDeploymentMedia $true`

**Comment by rbalsleyMSFT** [comment]
Also attach your c:\FFUDevelopment\FFUDevelopment.log. 

$CreateDeploymentMedia should be set to $true by default in the script itself.

**Comment by rbalsleyMSFT** [comment]
@heremansgeert based on your other issue, I assume you got this to work and I can close this?

**Comment by heremansgeert** [comment]
I was able to create the USB-drives on a different computer (laptop). I'm afraid the issue still persists on my desktop at work.

[FFUDevelopment.log](https://github.com/user-attachments/files/16760469/FFUDevelopment.log)

**Comment by rbalsleyMSFT** [comment]
Looks like -CreateDeploymentMedia is set to $false.

![image](https://github.com/user-attachments/assets/81e74357-ab4f-418b-859c-9af61fb802ce)

Like HedgeComp recommended, try setting -CreateDeploymentMedia $true in the command line. If that fails on your desktop at work, send over the FFUDevelopment log again.

**Comment by heremansgeert** [comment]
Hi,

This is the command used:

```powershell
C:\FFUDevelopment\BuildFFUVM.ps1 -ISOPath 'C:\FFUDevelopment\SW_DVD9_Win_Pro_11_23H2.8_64BIT_Dutch_Pro_Ent_EDU_N_MLF_X23-78772.ISO' `
-WindowsRelease 11 -WindowsSKU 'Education' `
-ProductKey 'N2983-4J894-QH6M4-MFRHJ-BWRB3' `
-WindowsLang 'nl-nl' `
-UpdateLatestCU $true `
-UpdateLatestNet $false `
-UpdateLatestDefender $false `
-UpdateEdge $false `
-UpdateOneDrive $false `
-InstallApps $true `
-InstallOffice $true `
-CleanupDrivers $false   `
-InstallDrivers $false `
-VMHostIPAddress '172.17.176.1' -VMSwitchName "Default Switch" `
-BuildUSBDrive $true `
-CopyUnattend $true `
-CopyAutopilot $true `
-Disksize 100GB `
-Processors 6 `
-Memory 10GB `
-verbose

```

Will try again and setting CreateDeploymentMedia explicit to $true.

**Comment by heremansgeert** [comment]
Yes, the command I pasted above was to indicate I got the errro without the -CreateDeploymentMedia switch set at all. My understanding was that this defaulted to $true.

After explicitly adding the switch I managed to create some USB's on my desktop.

Thank you for your help.

If I may I would like to ask a little question: Is there a way to quickly create more USB sticks after a succesfull build without going through the whole process again? I know I can stick multiple USB's in my computer to have them all converted to installable USB's. But is it possible to add a new batch of stick and have them use the same image without recreating the VM and such?

**Comment by HedgeComp** [comment]
> My understanding was that this defaulted to $true.

CreateDeploymentMedia - _When set to $true_, this will create WinPE deployment media for use when deploying to a physical device.

> is it possible to add a new batch of stick and have them use the same image without recreating the VM and such?

Thats a question for @rbalsleyMSFT .  You might be able to make USB from the WinPE_FFU_Deploy_x64.iso. 

I was thinking of this situation myself after a few test builds I did, that it would be handy.

**Comment by rbalsleyMSFT** [comment]
@MKellyCBSD wrote the USBImagingToolCreator.ps1 file that sits in the root of the FFUDevelopment folder. It's used for this exact purpose. His PR is #36 where he explains what the script does.

**Comment by heremansgeert** [comment]
Thank you all for helping me out! Have a nice day or evening.
