### ISSUE TITLE
Set correct Keyboard locale of installation

### ISSUE THREAD

**Issue by heremansgeert** [rbalsleyMSFT/FFU#56]
I was wondering how I could assure the correct keyboard locale is set for the installation.

In Belgium we use a AZERTY layout for our keyboards. The installation via FFU comes out as a QWERTY. I'm not sure but I'm guessing it's because this is the way the VM gets build? I use the language flag "nl-nl" so the language of the installation is correct. Only the locale should be "nl-be". 

I'm deploying using an autopilot JSON files which includes the correct settings. But I guess the locale settings will probably be applied after the user logs on the first time. Since the keyboard is in Qwerty this is  difficult and not something I can ask of my students.

```
{
    "CloudAssignedDomainJoinMethod":  0,
    "CloudAssignedDeviceName":  "%SERIAL%",
    "CloudAssignedAutopilotUpdateTimeout":  1800000,
    "CloudAssignedForcedEnrollment":  1,
    "Version":  2049,
    "CloudAssignedTenantId":  "John -middle name redacted - Swanson",
    "CloudAssignedAutopilotUpdateDisabled":  1,
    "ZtdCorrelationId":  "Some pounds, several inches",
    "Comment_File":  "Profile Autopilot profile without local admin richts",
    "CloudAssignedAadServerData":  "{\"ZeroTouchConfig\":{\"CloudAssignedTenantUpn\":\"\",\"ForcedEnrollment\":1,\"CloudAssignedTenantDomain\":\"sintcordula.be\"}}",
    "CloudAssignedOobeConfig":  1310,
    "CloudAssignedTenantDomain":  "domain.be",
    "CloudAssignedLanguage":  "nl-BE",
}
```

**Comment by heremansgeert** [comment]
Thank you for your help. I was indeed able to change the keyboard locale using the unattend file. I'm sorry that I din't try this first. Was trying to do this via a custom command that ran when the apps were installed.

**Comment by HedgeComp** [comment]
@heremansgeert  can you show an eaxmple of your untanntend.xml  WOuld like to see where you put the Keyboard layout. In the Specialize section or the OOBE section? thanks

**Comment by heremansgeert** [comment]
Sure,

here's my unattend_x64.xml files contents. Used [this site](https://schneegans.de/windows/unattend-generator/) to get the correct XML fields and settings for my locale.

```
<?xml version="1.0" encoding="utf-8"?>
<unattend xmlns="urn:schemas-microsoft-com:unattend">
 <settings pass="specialize">
    <component name="Microsoft-Windows-Shell-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <ComputerName>MyComputer</ComputerName>
    </component>
  </settings>
  <settings pass="windowsPE">
    <component name="Microsoft-Windows-International-Core-WinPE" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
      <SetupUILanguage>
        <UILanguage>nl-NL</UILanguage>
      </SetupUILanguage>
      <InputLocale>0813:00000813</InputLocale>
      <SystemLocale>nl-BE</SystemLocale>
      <UILanguage>nl-NL</UILanguage>
      <UserLocale>nl-BE</UserLocale>
    </component>
  </settings>

  <settings pass="oobeSystem">
    <component name="Microsoft-Windows-International-Core" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
      <InputLocale>0813:00000813</InputLocale>
      <SystemLocale>nl-BE</SystemLocale>
      <UILanguage>nl-NL</UILanguage>
      <UserLocale>nl-BE</UserLocale>
    </component>
  </settings>
</unattend>
```

**Comment by HedgeComp** [comment]
> here's my unattend_x64.xml files contents. Used [this site](https://schneegans.de/windows/unattend-generator/) to get the correct XML fields and settings for my locale.

thanks @heremansgeert  .. I use the same site.

You don't need to use the WinPE section, as @rbalsleyMSFT  confirmed in my #59  issue
