### ISSUE TITLE
"you cannot call a method on a null valued expression." Line 129, character 1 of the script

### ISSUE THREAD

**Issue by rbalsleyMSFT** [rbalsleyMSFT/FFU#6]
This is a great set of tools. Thank you!

Does the SSD of the target machine have to be in a certain condition prior to FFU application? ApplyFFU.ps1 throws an error indicating it "you cannot call a method on a null valued expression." Line 129, character 1 of the script. This happens if I wipe the SSD first with the BIOS utility or try to apply over an existing install.

_Originally posted by @jaywatkins in https://github.com/rbalsleyMSFT/FFU/issues/4#issuecomment-1835022877_

**Comment by jaywatkins** [comment]
Hi,

Here it is. Thanks again!

11/30/2023 9:06:47 AM Begin Logging
11/30/2023 9:06:47 AM Script version: 2309.2
11/30/2023 9:06:47 AM Physical DeviceID is 
11/30/2023 9:06:47 AM DiskID is 
11/30/2023 9:06:47 AM DiskID is not 0. Need to modify diskpart answer files
11/30/2023 9:06:47 AM Found 1 FFU File
11/30/2023 9:06:47 AM D:\Win11_22H2_Pro_Office_Sep2023.ffu will be installed
11/30/2023 9:06:47 AM No unattend folder found. Device name will be set via PPKG, AP JSON, or default OS name.
11/30/2023 9:06:47 AM No AP files found or AP was not selected
11/30/2023 9:06:47 AM Found 1 PPKG File
11/30/2023 9:06:47 AM D:\PPKG\Win11_092723-01.ppkg will be used
11/30/2023 9:06:47 AM Found 8 driver folders
11/30/2023 9:07:17 AM D:\Drivers\OptiPlex-7090 was selected
11/30/2023 9:07:17 AM Clean Disk
11/30/2023 9:07:17 AM Cleaning disk failed. Exiting

**Comment by rbalsleyMSFT** [comment]
This is returning nothing:

(Get-WmiObject -Class 'Win32_DiskDrive' | Where-Object {$_.MediaType -eq 'Fixed hard disk media' -and $_.Model -ne 'Microsoft Virtual Disk'}).DeviceID

Can you boot from the USB drive and when the command prompt window shows up where it's running wpeinit, immediately hit ctrl+c to stop it from running the powershell script. It should ask you to terminate the batch job. Hit Y. 

Then type powershell and hit enter
Then enter Get-WmiObject -Class 'Win32_DiskDrive' | select * | Out-file e:\disk.txt 

You might have to change the e:\disk.txt to d:\disk.txt.

Send me that disk.txt file. That should give me the disk configuration

Thanks,
Richard

**Comment by jaywatkins** [comment]
Thanks for your last response. I ran the commands and PowerShell threw a different error.

[disk_ps_eeror.txt](https://github.com/rbalsleyMSFT/FFU/files/13526511/disk_ps_eeror.txt)

**Comment by jaywatkins** [comment]
I can try the original device, the 7090, on Tuesday. I'll run memory diags on the one I have here (7060).

**Comment by rbalsleyMSFT** [comment]
Have you gotten the FFU process to work with other devices in the past? I see that the date on the FFU in the file name says Sep, so I'm assuming you built the FFU in the Sep time frame and it has been working with others?

**Comment by rbalsleyMSFT** [comment]
It isn't. It's just trying to hit the Win32_diskdrive class in WMI. This should be fairly easy to do from WinPE.

Good to hear this has worked before. For these devices, do they have any sort of 3rd party disk encryption or hardware encryption?



Thanks,
Richard
________________________________

**Comment by jaywatkins** [comment]
I didn't think it was that specific as far as the disk config. Would the script care if it was going to use an M.2 SSD vs. a SATA SSD? We only use the stock encryption tools, Bitlocker. Interesting you asked that because on some of these OptiPlex Micro's, Bitlocker is enabled by default without us setting it that way. Policy requires us to encrypt our laptops and that is done through software provisioning steps after Windows has been installed and gone through OOBE. This isn't the case for desktops. The only other measures take are Secure Boot. That's it.

**Comment by jaywatkins** [comment]
The 7060 passed all of its diags, including the extended memory test. Could a BIOS setting be getting in the way? We make several BIOS changes to all of our machines. One of which switches the disk controller from RAID to AHCI. 

Thanks again for your help

**Comment by rbalsleyMSFT** [comment]
It's possible. Could try changing that back or looking at other settings that may have been changed.

Thanks,
Richard
________________________________

**Comment by jaywatkins** [comment]
Richard,

When the disk controller on the 7090 was set to RAID (default), the ApplyFFU script throws the error mentioned above. Setting the controller to AHCI fixes that. Tested on several machines today.

**Comment by rbalsleyMSFT** [comment]
Thanks for the update, Jay.

You may be able to add storage drivers to PE then and it'll work when configured as RAID.

**Comment by jaywatkins** [comment]
I guess. I have all of the latest Dell drivers for WinPE as part of the driver set, but maybe there's some missing. We used to unilaterally disable the RAID option back in the Windows 7 days, when we were deploying with Ghost. Starting with Windows 7 and MDT, that setting didn't matter anymore.
