### ISSUE TITLE
Capturing FFU file fails with error ScriptHalted

### ISSUE THREAD

**Issue by robzilla10001** [rbalsleyMSFT/FFU#62]
As the title says, it goes through the whole process, shuts down the VM, checks for FFU files, finds none, fails, and then performs clean-up (removes VM, HGS Guardian certs, unused mountpoints) then spits out:

```
ScriptHalted
At C:\FFUDevelopment\BuildFFUVM.ps1:2765 char:13
+     throw $_
+     ~~~~~~
     + CategoryInfo              : OperationStoped: (:) [], RuntimeException
     + FullyQualifiedErrorId  : ScriptHalted
```

Can't find any info on a web search or in the other issues listed. Doesn't provide enough information for me to track down what went wrong.

**Comment by rbalsleyMSFT** [comment]
Can you attach the FFUDevelopment.log file? My guess is that the FFU didn't capture out of the VM, likely due to an issue with your VM Switch and IP address of that switch. That's usually the cause for an FFU to not get copied to the FFU folder. That's a tricky issue to log since the VM can't communicate back to the Host where the script is running, but I probably should add a better error if the FFU is missing to validate the Switch and IP setup.

**Comment by robzilla10001** [comment]
For sure, I believe it found the VM because it launched the VM and ran through a bunch of the setup process and all that jazz, but here's the log file for your perusal.
[FFUDevelopment.log](https://github.com/user-attachments/files/16910748/FFUDevelopment.log)

**Comment by rbalsleyMSFT** [comment]
It'll launch the VM without the Switch and IP address being correct. It's after the VM is done building where the switch gets added to the VM. If the switch name is wrong or the IP is wrong (or there's some other connectivity issue), after it boots the 2nd time to do the capture, it'll fail to capture to the host. 

![image](https://github.com/user-attachments/assets/fd58f8e0-3bf8-4767-8885-07eaa01b4aaa)

Can you run ipconfig /all and find the VM Switch New Virtual Switch adapter and send a screenshot of what that looks like? Should look something like this (New Virtual Switch) would be in parenthesis.

![image](https://github.com/user-attachments/assets/8a050e5c-86c0-4a2c-a1b0-35f1ad164857)

**Comment by robzilla10001** [comment]
![Screenshot 2024-09-06 125026](https://github.com/user-attachments/assets/6b8887dd-f8bd-4a4e-9d27-430d8f577d4e)
It looks like the IP address changed. Biscuits.

**Comment by rbalsleyMSFT** [comment]
This is actually good. I'll put some validation in that the VM Switch Name and IP address match before the script starts going so you can't get in this situation (unless the IP somehow changes while the script is running, but that's unlikely).

**Comment by robzilla10001** [comment]
I'm getting a different error now, but I have a feeling it's a connectivity issue. I'm about to jump on the phone with MSFT for another issue and will try again afterwards. Thanks for the prompt responses and pointing me in the right direction!
