### ISSUE TITLE
New PPKG and Unattend Validation logic is NULL

### ISSUE THREAD

**Issue by HedgeComp** [rbalsleyMSFT/FFU#63]
The New Validate PPKG and Unattend Folder logic throws error on script runs because your variables for $PPKGFolder and $UnattendFolder are never defined. See error message example if `-CopyUnattend` `$true`

![image](https://github.com/user-attachments/assets/5f552cea-b955-434a-b304-2c2326eb7317)

I have defined them with "$FFUDevelopmentPath\\__foldername_" in

**Comment by rbalsleyMSFT** [comment]
Yeah, I've fixed it already, just haven't committed it. There are some other things I'm testing before getting 2409.1 out.
