### ISSUE TITLE
Naming Device - First 7 of serial

### ISSUE THREAD

**Issue by robzilla10001** [rbalsleyMSFT/FFU#66]
I watched your deep dive video and couldn't figure out another way to contact you other than this. In the video, you say if you want to customize the naming convention, you have to edit the script. Could you point me in the right direction to make it take my prefix and append the first 7 of the serial? We work with Lenovo's and the serial numbers are too long for our purposes.

**Comment by HedgeComp** [comment]
Hi @robzilla10001 you can put your Prefix in the Prefixes.txt.  If you only put one, then it won't prompt and simply apply the single prefix.

To change the code, you need to go to /FFUDevelopment/WinPEDeployFFUFiles/ApplyFFU.ps1. On line 259 you can make your changes as needed., for example:

`$serial = (Get-CimInstance -ClassName win32_bios).SerialNumber.Trim().Substring(0, 7)`

BTW, we use Lenovo and its only 8 Characters for the Serial, so we try and keep the Prefixes abbreviated enough that the entire Serial number can be added to the computer name and still come in under the 15 Character Limit for Windows device Names.

**Comment by robzilla10001** [comment]
Thanks, will take a look on Monday and see how this turns out. Thanks again for all the help!
