### ISSUE TITLE
Device Naming

### ISSUE THREAD

**Issue by robzilla10001** [rbalsleyMSFT/FFU#67]
Trying to keep this to one issue per post.

I have the prefix set in the folder and the unattend is set to the default:

```
<?xml version="1.0" encoding="utf-8"?>
<unattend xmlns="urn:schemas-microsoft-com:unattend">
  <settings pass="specialize">
    <component name="Microsoft-Windows-Shell-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <ComputerName>MyComputer</ComputerName>
    </component>
  </settings>
</unattend>
```

However, if I jump into audit mode from OOBE, it's giving me DESKTOP-%RANDOM% as the computer name. Did I miss a step? I rewatched the pertinent portion of your deep dive video and re-read the document and haven't been able to nail it down.

**Comment by rbalsleyMSFT** [comment]
If you just let it boot like normal and at the OOBE screen hit shift+f10 and type hostname, is the name right?

**Comment by robzilla10001** [comment]
No, it's still following the DESKTOP-%RANDOM% naming convention.
![image](https://github.com/user-attachments/assets/97391596-71c1-4f7e-a7cf-997d1f9d72ab)

**Comment by robzilla10001** [comment]
It forces me to specify a computer name, but I go into advanced once I have the wizard completed and remove the naming convention before finalizing the PPKG. Plus, I'm never actually making it to the point of the PPKG being processed.

**Comment by HedgeComp** [comment]
Do you have more then one Prefix in your Prefixes.txt file?

**Comment by HedgeComp** [comment]
> It forces me to specify a computer name, but I go into advanced once I have the wizard completed and remove the naming convention before finalizing the PPKG.

Ok, this is what I was getting at. I do the same. Start the Wizard and then switch to Advanced to Delete the Computer name section.

**Comment by robzilla10001** [comment]
Negative, just the one. We use just a single prefix in our environment (used to be 2 to reflect laptop vs desktop but simplified when we began trying to make Autopilot work).

**Comment by HedgeComp** [comment]
> Negative, just the one. We use just a single prefix in our environment (used to be 2 to reflect laptop vs desktop but simplified when we began trying to make Autopilot work).

To trouble shoot more, I'd either remove the prefixes.txt file all together or add more prefixes just for testing. It should either ask you to manually name the Device if no prefix found or you can select from a list.

The device Name should be written inside Unattend.xml.

**Comment by robzilla10001** [comment]
I'll remove the prefixes folder and rebuild the iso and see what happens. In Unattend_x64.xml inside C:\FFUDeployment\unattend, the computer name is listed as MyComputer, as shown in Richard Balsley's deep dive video. If that should be changed, please advise, as I have changed the behavior of the PS1 script as he recommended on a previous issue. Here's the block from ApplyFFU.ps1:

```
    elseif ($UnattendPrefixCount -eq 1) {
    WriteLog "Found $UnattendPrefixCount Prefix"
    $PrefixToUse = $UnattendPrefixes[0]
    WriteLog "Will use $PrefixToUse as device name prefix"
    }
    #Get serial number to append. This can make names longer than 15 characters. Trim any leading or trailing whitespace
    $serial = (Get-CimInstance -ClassName win32_bios).SerialNumber.Trim().Substring(0, 8)
    #Combine prefix with serial
    $computername = ($PrefixToUse + $serial) -replace "\s","" # Remove spaces because windows does not support spaces in the computer names
    #If computername is longer than 15 characters, reduce to 15. Sysprep/unattend doesn't like ComputerName being longer than 15 characters even though Windows accepts it
    If ($computername.Length -gt 15){
       $computername = $computername.substring(0,15)
```

**Comment by HedgeComp** [comment]
> $serial = (Get-CimInstance -ClassName win32_bios).SerialNumber.Trim().Substring(0, 8)

I see you changed it 8 from the 7 you wanted. I do believe that Lenovo is already 8 for Serials , so it not needed. I use Lenovo exclusively now and we don't need to trim the serial number. We simply keep the Prefix, including the "-" to 7 characters so we come in under the required 15 limit for Hybrid Joined devices.

Also , the Unattend_x64.xml contects will be copied and renamed to "Unattend.xml" and placed in the folder for your Deploy media automatically. 

The tricky thing with the XML is to have the correct Order and components listed correctly and not duplicated.

Heres an example of the 

```<?xml version="1.0" encoding="utf-8"?>
<unattend xmlns="urn:schemas-microsoft-com:unattend" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State">
  <settings pass="specialize">
    <!--ComputerName must be in the first Component Element  -->
    <component name="Microsoft-Windows-Shell-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <ComputerName>MYCOMPUTER</ComputerName>
      <TimeZone>Eastern Standard Time</TimeZone>
    </component>
    <!-- Place additional Settings or Component Elements below here: -->
    <component name="Microsoft-Windows-Deployment" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <RunASynchronous>
        <RunASynchronousCommand wcm:action="add">
          <Order>1</Order>
          <Path>cmd.exe /c date 09-07-2024</Path>
          <Description>Set system date to a specific date</Description>
        </RunASynchronousCommand>
      </RunASynchronous>
    </component>
  </settings>
  <settings pass="oobeSystem">
    <component name="Microsoft-Windows-International-Core" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
      <InputLocale>0409:00000809</InputLocale>
      <SystemLocale>en-US</SystemLocale>
      <UILanguage>en-US</UILanguage>
      <UserLocale>en-US</UserLocale>
    </component>
    <component name="Microsoft-Windows-Shell-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
      <OOBE>
        <ProtectYourPC>3</ProtectYourPC>
        <HideEULAPage>true</HideEULAPage>
        <HideWirelessSetupInOOBE>false</HideWirelessSetupInOOBE>
      </OOBE>
    </component>
  </settings>
</unattend>
```

**Comment by robzilla10001** [comment]
I ended up changing it to 8 to accommodate M$ Surfaces (they unfortunately do have long serial numbers), not Lenovo's as I previously thought. Thanks for sharing your unattend.

**Comment by HedgeComp** [comment]
> Thanks for sharing your unattend.

No problem, had done alot of trial and error on the xmls to get it working well . I am going to make a pull request to add a sample to share with others if it can help them.

**Comment by rbalsleyMSFT** [comment]
I don't understand the need to set a substring after the Trim that's already done. Since Unattend doesn't support names being longer than 15 (even though Windows supports longer names), the script already truncates to 15 characters (the prefix + the serial). 

So if I have a prefix of ABCD- and my serial is 12345678910111213, the name should be ABCD-1234567891. That's the whole point of the If statement.

If that's not happening, then there's a bug. Shouldn't be a need to adjust the number of characters taken from the serial number.

**Comment by robzilla10001** [comment]
The way our environment is setup, they prefer a specific character length for the computer names for uniformity.

This is working now btw. Am closing the issue, thanks for all the help @HedgeComp @rbalsleyMSFT
