### ISSUE TITLE
OOBE doesn't find PPKG

### ISSUE THREAD

**Issue by robzilla10001** [rbalsleyMSFT/FFU#68]
As the title says, when I get to OOBE, I hit the windows key five times and click install provisioning packages. However, it's not finding the package. I have tried putting it on the root of the deploy partition, and I've tried putting it in the PPKG folder, but it doesn't find it in either case. Am I missing something? For reference, I am performing this deployment in a Hyper-V VM, but I have the Deploy partition set up correctly (it finds and applies the FFU without issue) so I don't think that's the problem. I work remotely, so I will have to have someone test this tomorrow with real media but I'm hoping to sort my issues before then so we can be locked and ready to rock.

**Comment by rbalsleyMSFT** [comment]
So I assume you have a VHDX that has your FFU and PPKG on it?

OOBE is designed to look for the PPKG via removable media or an ISO (so it won't find it on the VHDX). If using a Hyper-V VM and testing the PPKG, you'll want to put the PPKG file on an ISO and mount the ISO once in OOBE and hit the windows key five times.

**Comment by robzilla10001** [comment]
Ok, created the iso in IMGburn with label DEPLOY, added it with the following settings, still getting the message that no provisioning packages could be found. 
![image](https://github.com/user-attachments/assets/3c788547-b02d-4d03-9cc1-aafbe0b31d85)

**Comment by HedgeComp** [comment]
@robzilla10001 Are you creating an actual USB Drive that's attached to your PC currently? If so you can can mount it to the VM and boot  off the USB drive inside the VM. This is what I do to emulate the entire process with the physical USB drive I 've created.

**Comment by robzilla10001** [comment]
I haven't started building the ISO yet as I'm still in the testing phase, so I'm just building ISO's. Also, this is a remote device so I'm relying on other people to plug and unplug hardware from the machine and performing everything via RDP.

**Comment by HedgeComp** [comment]
ok that makes it more interesting for sure.. 😕 

can you show the Filexploere view  of your Depoloy.iso and the Deploy_x64.iso?

**Comment by robzilla10001** [comment]
Sorry, that previous response was confusing. I haven't started building USB's yet as I'm still testing. Here are the iso's:
![image](https://github.com/user-attachments/assets/95e4e562-7c36-4b3b-bb65-b91ea9f35ba3)
and the winpe deploy iso is filled with folders pertaining to languages (en-us for instance) and sources folder, bootmgr and bootmgr.efi

**Comment by HedgeComp** [comment]
I don't see your Unattend Folder.

Heres how it looks when you create the USB Drive.
![image](https://github.com/user-attachments/assets/a046e544-77d6-4f6c-95a3-7250f1b42033)

**Comment by robzilla10001** [comment]
I used the -CopyUnattend switch when building, I wonder why it didn't copy. OK, I will manually add the unattend before re-running the install. Luckily this process is very quick ^__^

**Comment by HedgeComp** [comment]
> I used the -CopyUnattend switch when building, I wonder why it didn't copy. OK, I will manually add the unattend before re-running the install. Luckily this process is very quick ^__^

Are you running the "Main" Branch or the "2409.1" Branch?

**Comment by robzilla10001** [comment]
2408.1, I will give that a shot, thanks.

**Comment by robzilla10001** [comment]
Going to show I'm a bit of a Github noob at this point, but alas, here we are. I click on 2409.1, but I can't figure out how to download it as it's showing the most recent release as being the 2408.1 that I already have. Is there some way to download the FFUDeployment folder as a whole that I'm missing?

**Comment by HedgeComp** [comment]
Yes make please make it a seperate issues, its easier for everyone and if its discovered to be a bug can be addresses in a new update or Pull request.

If the previous problem is solved, please close this issues.

Cheers

**Comment by robzilla10001** [comment]
Rebuilding with 2408.1 and using a USB drive this time, will close if issue is resolved.

**Comment by rbalsleyMSFT** [comment]
After the FFU has been deployed, go into the Hyper-V VM and remove the Deploy ISO and select your ISO with the PPKG on it.

![image](https://github.com/user-attachments/assets/7c18a091-d35a-4f85-9bf5-57932e41a46d)

The ISO itself should have the PPKG in the root, it shouldn't be in a PPKG folder. Windows doesn't understand that and won't find the PPKG file. The below screenshot is an ISO with my WCD project folder. You don't need all the project files, just the .PPKG file, but when I created the ISO I just took the entire folder. 

![image](https://github.com/user-attachments/assets/a5968d0a-3303-4f7a-9722-b7c3ea47eafa)

Once the new ISO has been mounted to the VM, hit the Windows key 5 times and the menu should pop up to select the PPKG.

**Comment by robzilla10001** [comment]
> @robzilla10001 Are you creating an actual USB Drive that's attached to your PC currently? If so you can can mount it to the VM and boot off the USB drive inside the VM. This is what I do to emulate the entire process with the physical USB drive I 've created.

How do you manage this? I haven't found a way to mount the physical drive in the Hyper-V VM.

@rbalsleyMSFT I just built a USB and it placed the PPKG in a folder titled PPKG, so I copied it out and deleted the folder. Does the unattend file remain in the unattend folder as the deploy media was built or do I need to move it elsewhere as well?

**Comment by HedgeComp** [comment]
> How do you manage this? I haven't found a way to mount the physical drive in the Hyper-V VM.

Its a two step process. As you can't share a USB with the Host machine and the  VM at the same time. Do this.

1. Go Disk MAnagement select your USB disk and then right click and Select Offline
![image](https://github.com/user-attachments/assets/d816a7fb-e3a8-4a6c-8aa9-cec21da99746)
it will appear offline
![image](https://github.com/user-attachments/assets/81831c9a-9428-4ba7-adb2-b09f63d6b4e8)

2.  In your Test VM Add another Hard Dirve and select Physical Hard Disk.
![image](https://github.com/user-attachments/assets/9cef0e70-8e4c-4c66-a388-6e3a3fa52cb9)


This is how I like to test my new builds with the exact USB that I am going to use on the physical Mahchine.

**Comment by HedgeComp** [comment]
> @rbalsleyMSFT I just built a USB and it placed the PPKG in a folder titled PPKG, so I copied it out and deleted the folder. Does the unattend file remain in the unattend folder as the deploy media was built or do I need to move it elsewhere as well?

If you look at my screehshot above. This is how the root deploy drive should look:
![image](https://github.com/user-attachments/assets/cb4b4809-14cd-4be8-b5bf-971837357eaa)

The PPKG File should be copied to the root for you, but if not place as it is the scrren above.

THen keep your Unattend files in the Unattend Folder. This where the Copmuter naming kicks in. If you move it out or don't have it then you will get an error and most likely why you are not naming the PC correctly. 
this is how the Unattend folder should look like:

![image](https://github.com/user-attachments/assets/859f7705-016b-404b-a452-8e9f727e3759)

**Comment by robzilla10001** [comment]
Mine doesn't have the offline option.

![image](https://github.com/user-attachments/assets/8747c384-484b-4702-b2d5-c03a967e3b89)

@rbalsleyMSFT Got it. I will leave the unattend as is.

**Comment by HedgeComp** [comment]
> Mine doesn't have the offline option.

Sorry I've been using USB 3.2 Gen2s so they are present as External Hard Drives to the OS. I don't believe you can Offline a removable Storage Device. 

Just keep the Unattend_x64.xml where it is in your Deployment folder. The script will copy the contents to your Deployment Drive, put it in the "unattend" folder and then rename it correctly to unattend.xml.  

If you have made any changes or customizations to your xml. You can post it in my closed issue #59 . I'll take a look at it if you like.

**Comment by HedgeComp** [comment]
> I used the -CopyUnattend switch when building, I wonder why it didn't copy. OK, I will manually add the unattend before re-running the install. Luckily this process is very quick ^__^

just reread this you need the -CopyPPKG $true as well.

**Comment by rbalsleyMSFT** [comment]
> > @robzilla10001 Are you creating an actual USB Drive that's attached to your PC currently? If so you can can mount it to the VM and boot off the USB drive inside the VM. This is what I do to emulate the entire process with the physical USB drive I 've created.
> 
> How do you manage this? I haven't found a way to mount the physical drive in the Hyper-V VM.
> 
> @rbalsleyMSFT I just built a USB and it placed the PPKG in a folder titled PPKG, so I copied it out and deleted the folder. Does the unattend file remain in the unattend folder as the deploy media was built or do I need to move it elsewhere as well?

The unattend stuff happens within WinPE, so as @HedgeComp mentioned, the unattend folder needs to be on the deploy drive. The copying of unattend shouldn't be an issue whether doing it through Hyper-V or physical.

The PPKG stuff can be harder to test though because that's all done during OOBE and Windows will only look for a PPKG automatically if a removable drive is present, hence the need to do the Windows key 5 times to get the PPKG menu item to pop up. I prefer doing the ISO method like I mentioned above and just swapping to the PPKG ISO once I get to OOBE. 

It might also help if you post your scriptlog.txt file from the Deploy drive if you're still having issues.

**Comment by robzilla10001** [comment]
Will let you know tomorrow when I have a technician in that office to test the drive I built (it didn't finish until they'd gone home for the evening) and I'm having an issue with my VM at the moment.

**Comment by robzilla10001** [comment]
I believe this is resolved. I am getting an error message with my PPKG (0x800700b7), but I believe that may be because the device name was already in use in AAD/Intune (it created duplicates, so I'm not sure). But that's something I have to work through elsewhere. Thanks again for all the help @rbalsleyMSFT @HedgeComp
