### ISSUE TITLE
2409.1 - Error during build process.

### ISSUE THREAD

**Issue by robzilla10001** [rbalsleyMSFT/FFU#69]
Getting the following error attempting to build with 2409.1, currently reverted to 2408.1 so I could build a drive but wanted to put this issue on the radar, in case it's not user error.

```
VERBOSE: Searching for Update for Microsoft Defender Antivirus antimalware platform from Microsoft Update Catalog and
saving to C:\FFUDevelopment\Apps\Defender
Creating Apps ISO Failed
VERBOSE: Creating Apps ISO Failed with error Unable to connect to the remote server
Invoke-WebRequest : Unable to connect to the remote server
At C:\FFUDevelopment\BuildFFUVM.ps1:2168 char:16
+ ...  $results = Invoke-WebRequest -Uri "http://www.catalog.update.microso ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

**Comment by rbalsleyMSFT** [comment]
I don't think that's an issue with 2409.1. That code should be the same with 2408.1 and 2409.1.

I just tested on 2409.1 and it's working here. Could be an intermittent network issue connecting to Microsoft Update.

![image](https://github.com/user-attachments/assets/59b9fd7a-0260-412b-a4b5-9b4a091bcdad)

**Comment by robzilla10001** [comment]
I've had the issue intermittently with 2408.1 but it was constant with 2409.1. Will give it another go after this drive builds.

**Comment by HedgeComp** [comment]
I 'd suggest you also simply copy the URL from the error and see if you can open a browser and download it manually. If you can't , then I would also agree that  it would an issue with connecting to the MS catalog. Could be your internet is having an issue from one hop to the next.   You could also rule try doing issues by doing some Tracert s to see if you can find your way there.

as  @rbalsleyMSFT  said, the code is been the same and I 've only had issues when I was my own workstation having issues getting to the MS sites.

**Comment by rbalsleyMSFT** [comment]
@robzilla10001 is this still an issue, or can it be closed?

**Comment by robzilla10001** [comment]
@rbalsleyMSFT It still fails for me if I have Defender update or Cumulative update on in 2409.1; I just checked it again. It occasionally fails in 2408.1 (I'd say it's successful 8 of 10 times) but it's a 100% failure rate for me on 2409.1. Not sure why, but cannot communicate with the microsoft servers with 2409.1

**Comment by rbalsleyMSFT** [comment]
If you put this in Edge or Chrome, does it download?

https://catalog.s.download.windowsupdate.com/d/msdownload/update/software/defu/2024/07/updateplatform.amd64fre_cac3b1186fe95576888045e13716bd460be70cf3.exe

**Comment by robzilla10001** [comment]
Yes it does. Connects immediately.

**Comment by rbalsleyMSFT** [comment]
Do you have an EDR/XDR or security software on the machine? I wonder if that somehow sees that there's a PowerShell script going outbound to download something and it's getting filtered.

**Comment by robzilla10001** [comment]
It did stop AADInternals from installing (I was having trouble making the PPKG on this machine so had to do it on another), but it allows the 2408.1 version to download it, why would it treat it any differently? To answer your question, I'm fairly certain we do, but I don't know that it's the culprit here, as I'm not getting any notifications from defender or sentinel.

**Comment by rbalsleyMSFT** [comment]
I don't know why 2408 or 2409 would be any different. That part of the code hasn't changed.

It's possible you don't see any notifications on the client side. Could also be something on the network that may filter the traffic if it looks suspicious. I'd try running on another machine if you can, one that isn't managed by your organization if possible.

**Comment by robzilla10001** [comment]
I unfortunately don't possess a personal Windows device, or have access to one. Wife is all Mac and I use Debian on my home personal device.

I didn't mean on the client side, I'm on the security team so if it was triggering any rules in Defender or Sentinel, I would assume it drop an alert or incident and I could investigate. I guess I'll just stick with 2408 for now, as it's working for me. Just gotta get my provisioning package fixed and I'll be good to go.
