### ISSUE TITLE
Surface Drivers Not Downloading

### ISSUE THREAD

**Issue by d12ts** [rbalsleyMSFT/FFU#76]
Downloaded current version 2409.1 and have tried different model names, but no matter what I still get the same result: "Please select a model from the list below by number:" It does not show a list of models and I have tried writing them exactly as the show up per link it goes to and your example youtube video that shows the list. Any ideas? 

Thanks

![Screenshot 2024-09-16 161315](https://github.com/user-attachments/assets/d52906eb-6566-4095-a79c-40759c84c6bc)

**Comment by rbalsleyMSFT** [comment]
Thanks for the issue. Looks like the page has changed. The drop down looks slightly different. I'll investigate tomorrow.

**Comment by rbalsleyMSFT** [comment]
This should be fixed in #77

**Comment by d12ts** [comment]
Thank you sir!

**Comment by gorilla1968** [comment]
Thank you!
