### ISSUE TITLE
oscdimg does not support long path

### ISSUE THREAD

**Issue by LaurentLouf** [rbalsleyMSFT/FFU#80]
Hello,

First of all thanks for the great tool, it is really helpful ! 

I have however stumbled upon a limitation with one of the ADK executables, _oscdimg_, that does not seem to support long path (> 260 characters). As an easy fix, I've tried mapping the Apps folder as a drive using the command _subst_. But well, what should have happened has happened and I'm still stuck with another path that is too long.

Too bad as oscdimg is a nice one-liner but I'll try with https://github.com/TheDotSource/New-ISOFile and keep you posted here.

**Comment by rbalsleyMSFT** [comment]
Can you try setting LongPath support?

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem

Set LongPathsEnabled = 1 (REG_DWORD)

Let me know if that works (preferably without a reboot). If it works without a reboot, we could make the change in the script to enable it and then set it back when finished. I've actually run into issues with long paths and driver downloads (can't remember the exact problem, think BITS didn't like the length of the path or something). So it's possible this fix could help a couple of things.

**Comment by LaurentLouf** [comment]
Seems like I forgot to mention that I did try that without success. The
register and the group policy (though they might be the same thing)

**Comment by rbalsleyMSFT** [comment]
Did you try a reboot?

**Comment by LaurentLouf** [comment]
I already had to set this registry key a long time ago, so I didn't need to
set actually this time. Since I didn't have to change the value, I also
didn't reboot as there was nothing to "apply".

By the way, the New-ISOFile that I mentioned at the beginning is working as
far as I know as expected

**Comment by rbalsleyMSFT** [comment]
I think we need to do two things. 

1. Enable Long Path support
2. Use \\?\. in front of the apps path

With just Long Path support enabled in the registry, I can get a script to create a path longer than 300 characters, but oscdimg fails to create the ISO. If I don't add the long path support, it doesn't create the complete directory path

![image](https://github.com/user-attachments/assets/0023a885-d8a2-4e45-b35c-5d270d64ed46)

If I add \\?\ in front of the directory path to generate the ISO, it works.

![image](https://github.com/user-attachments/assets/23b48723-f7ac-4942-8275-d63f34a64deb)

Can you try modifying the New-AppsISO function by adding:

`$appsPath = "\\?\" + $appsPath #Add the \\?\ prefix to the path to allow for long file names`

before

`Invoke-Process $OSCDIMG "-n -m -d $Appspath $AppsISO"`

Seems to create the ISO for me without an issue. I don't have any apps though with the pathing issues you do, so it'd be good to know if this works for you. If it does, I'll need to add Long Path support plus this fix.

**Comment by rbalsleyMSFT** [comment]
Thanks, glad to hear it's working.

Are you building on ARM64 devices?

**Comment by LaurentLouf** [comment]
No, just amd64

**Comment by rbalsleyMSFT** [comment]
This has been fixed in 2412.1.
