### ISSUE TITLE
Capture Media Failed Message 

### ISSUE THREAD

**Issue by achawla29** [rbalsleyMSFT/FFU#92]
Could I please get some help with the attached error message, have tries 2-3 tries but it keeps failing at the same spot. Once the VM Starts I get the below error message in the PowerShell window

VERBOSE: Mounting WinPE media to add WinPE optional components
VERBOSE: Mounting complete
VERBOSE: Adding Package WinPE-WMI.cab
Creating capture media failed
VERBOSE: Creating capture media failed with error The request is not supported.
VERBOSE: Dismounting image at C:\FFUDevelopment\WinPE\mount

LogPath : C:\Windows\Logs\DISM\dism.log

VERBOSE: Successfully dismounted image at C:\FFUDevelopment\WinPE\mount
VERBOSE: Remove unused mountpoints
VERBOSE: Removal complete
Add-WindowsPackage : The request is not supported.
At C:\FFUDevelopment\BuildFFUVM.ps1:2942 char:9
+         Add-WindowsPackage -Path "$WinPEFFUPath\mount" -PackagePath $ ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-WindowsPackage], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.AddWindowsPackageCommand

PS C:\FFUDevelopment>

![Error3_FFU](https://github.com/user-attachments/assets/e93a97fc-1be8-4478-ab32-170deb8dcc3f)

Also, please find the attached DISM and FFUDevelopment log files

[dism.log](https://github.com/user-attachments/files/17375815/dism.log)
[FFUDevelopment.log](https://github.com/user-attachments/files/17375821/FFUDevelopment.log)

I am using the below command for the solution 

.\BuildFFUVM.ps1 -WindowsSKU 'Pro' -Installapps $true -InstallOffice $true -InstallDrivers $true -CopyDrivers $true -VMSwitchName 'External' -VMHostIPAddress '192.168.0.14' -CreateDeploymentMedia $true -BuildUSBDrive $true -UpdateLatestCU $false -UpdateLatestNet $true -UpdateLatestDefender $true -UpdateEdge $true -UpdateOneDrive $true -RemoveFFU $true -WindowsRelease 10 -WindowsVersion '22H2' -Verbose -CopyUnattend $true

Thanks for the help in advance

**Comment by achawla29** [comment]
Thanks a lot for getting back.

Sure, I will upgrade my host machine to Windows 11 and give it another go.

Really excited to get this working, it would save us lot of time, thanks again

**Comment by rbalsleyMSFT** [comment]
Let me know how it goes so I can close the issue. Thanks!

**Comment by achawla29** [comment]
Thanks for the tip, I was able to build the FFU with off the domain the Windows 11 PC, something was definitely blocking some dism commands on the domain joined machine.

Could I ask couple more questions on the workflow, happy to raise another issue if you want

- Do we suppose to shutdown the VM manually after apps installation, sysprep etc?

- After applying the FFU on the physical test machine, machine logged in automatically with administrator account and sysprep window was displayed with reboot option, is that how it supposed to work? Please see the attached pic below

![image](https://github.com/user-attachments/assets/0b8790e2-6f72-40d9-9670-eaec5e25e451)

Thanks for your help so far

**Comment by achawla29** [comment]
Please close the ticket, I have managed to fix the sysprep (audit mode) issue.

Thanks for your help for the great solution
